- hosts: myhost
  become: yes
  tasks:
    - name: Allow new incoming SYN packets on TCP port 22 (SSH)
      iptables:
        chain: INPUT
        protocol: tcp
        destination_port: 22
        ctstate: NEW
        syn: match
        jump: ACCEPT
        comment: Accept new SSH connections.
    - name: Allow new incoming SYN packets on TCP port 80 (HTTP)
      iptables:
        chain: INPUT
        protocol: tcp
        destination_port: 22
        ctstate: NEW
        syn: match
        jump: ACCEPT
        comment: Accept new HTTP connections.
    - name: Add Docker repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docer-ce.repo
      become: yes
    - name: Enable Docker Edge repo
      ini_file:
        dest: /etc/yum.repos.d/docer-ce.repo
        section: 'docker-ce-edge'
        option: enabled
        value: 0
      become: yes
    - name: Install Docker
      package:
        name: docker-ce
        state: latest
      become: yes
    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
      become: yes
    - name: Install Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/download/1.25.1/docker-compose-Linux-x86_64
        dest: "/usr/local/bin/docker-compose"
        mode: 0755
    - name: Start container with healthstatus
      docker_container:
        name: nginx-proxy
        image: nginx:1.13
        state: started
        healthcheck:
        # Check if nginx server is healthy by curl'ing the server.
        # If this fails or timeouts, the healthcheck fails.
        test: ["CMD", "curl", "--fail", {{inventory_hostname}}]
        interval: 1m30s
        timeout: 10s
        retries: 3
        start_period: 30s